name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show Node version
        run: node -v

      - name: Show npm version
        run: npm -v

      - name: Install project dependencies
        run: npm install

      - name: Show repository structure
        run: ls -R
